#!/bin/bash
# 测试 EventKit 权限请求修复

echo "========================================="
echo "EventKit 序列化修复验证"
echo "========================================="
echo ""
echo "已修改的返回语句："
echo "  - gd_eventkit_request_calendar_access() x2"
echo "  - gd_eventkit_request_reminders_access() x2"
echo ""
echo "修改内容："
echo "  旧: return ...GDDupNSString(statusString)..."
echo "  新: NSString *jsonString = [NSString stringWithFormat:@\"\\\"%@\\\"\", statusString];"
echo "      return ...GDDupNSString(jsonString)..."
echo ""
echo "预期效果："
echo "  ✓ Objective-C 返回 \"denied\" (带引号的 JSON 字符串)"
echo "  ✓ Rust serde_json::from_str() 能正确反序列化"
echo "  ✓ 不再报错 'expected value at line 1 column 1'"
echo ""
echo "验证步骤："
echo "  1. cd /Users/zonkidd/IdeaProjects/goal-desk-tauri"
echo "  2. npm run tauri:dev"
echo "  3. 触发权限请求（首次启动应自动触发）"
echo "  4. 观察控制台，应该没有反序列化错误"
echo ""
echo "如果仍有问题，检查："
echo "  - 权限状态是否为 'denied'（可能需要重置 TCC）"
echo "  - Rust 日志中 payload 的实际内容"
echo "  - 是否有其他 EventKit 函数也返回裸字符串"
echo ""
echo "========================================="
